version: '2'
services:

#  vpn:
#    container_name: vpn
#    image: dperson/openvpn-client:latest
#    cap_add:
#      - net_admin # required to modify network interfaces
#    restart: unless-stopped
#    volumes:
#      - /dev/net/tun:/dev/net/tun # tun device
#      - ${HOME}/.vpn:/vpn # OpenVPN configuration
#    ports:
#      - 8112:8112 # port for deluge web UI to be reachable from local network
#    command: '-r 192.168.1.0/24' # route local network traffic

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: host #service:vpn # run on the vpn network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/ubuntu/downloads:/downloads # download folder
      - /mnt/storage/configs/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/downloads/blackhole:/downloads
      - /mnt/storage/configs/jackett:/config
    ports:
      - 9117:9117

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/configs/nzbget:/config
      - /home/ubuntu/downloads:/downloads
      - /mnt/storage:/storage
    ports:
      - 6789:6789

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage:/storage
      - /mnt/storage/configs/sonarr:/config
    ports:
      - 8989:8989

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage:/storage
      - /mnt/storage/configs/radarr:/config
    ports:
      - 7878:7878

  emby:
    container_name: emby
    image: emby/embyserver:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - UID=1000
      - GID=1000
      - GIDLIST=1000
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/storage/configs/emby:/config
      - /mnt/storage/media:/mnt/share1

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/media/movies:/movies
      - /mnt/storage/media/tv:/tv
      - /mnt/storage/configs/bazarr:/config
    ports:
      - 6767:6767

#  plex-server:
#    container_name: plex-server
#    image: plexinc/pms-docker:latest
#    restart: unless-stopped
#    environment:
#      - TZ=Europe/Paris # timezone
#    network_mode: host
#    volumes:
#      - ${HOME}/.plex/db:/config # plex database
#      - ${HOME}/.plex/transcode:/transcode # temp transcoded files
#      - /media/${USER}/data1/downloads:/data # media library
